### ISSUE TITLE
Add color to reply

### ISSUE THREAD

**Issue by joan-carles** [lmatosevic/chatgpt-cli#1]
Hi,

I few enhancements to improve usability:

1-  Would be useful to add colors. For instance "IA" to type in white color and "YOU" in yellow or green for instance.

2- Also would be good to limit width of the text. 

Thanks

**Comment by lmatosevic** [comment]
Hi Joan Carles,

Thank you for your feedback. The new branch is created and this feature will be implemented in the coming days.

**Comment by lmatosevic** [comment]
The new version 1.4.0 is out. Both usability features are implemented and are completely configurable and optional to use.

You can update your .env file with the following values to configure colors and max text width.

```
CHAT_TEXT_WIDTH=1024

CHAT_COLORED=true
CHAT_COLOR_YOU=green
CHAT_COLOR_AI=white
```

You can specify separately the color of your inputs and the AI responses.
