### ISSUE TITLE
Writing the history to file

### ISSUE THREAD

**Issue by catanadj** [lmatosevic/chatgpt-cli#3]
Hi! 

Could the history be written to file to be kept as a reference ?

Thank you.

Kind regards.

**Comment by lmatosevic** [comment]
Hello,

Thanks for this suggestion, it could be very useful for keeping the conversation record for later use.

I will try to implement this feature in the coming days.

**Comment by lmatosevic** [comment]
This feature is now released in version 1.5.0

The chatgpt-cli command is extended with an additional argument `[file_out]` which can be used to specify the destination of the file in which to save the chat conversation.

Example usage:
```
chatgpt-cli ./path/to/chat.txt
```

You can find more details in this readme section: https://github.com/lmatosevic/chatgpt-cli#chatgpt-cli-api_key-file_out
